name: clash_companion
description: Clash Companion - League of Legends Clash Tournament Management
publish_to: 'none'
version: 1.1.1+alpha

environment:
  sdk: '>=3.0.0 <4.0.0' 

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_local_notifications: ^17.1.2
  package_info_plus: ^4.2.0
  cupertino_icons: ^1.0.6
  http: ^1.1.0
  go_router: ^12.1.3
  shared_preferences: ^2.2.2
  intl: ^0.20.2
  web_socket_channel: ^2.4.0
  google_sign_in: ^7.2.0
  cached_network_image: ^3.3.1
  carousel_slider: ^5.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  integration_test:
    sdk: flutter
  golden_toolkit: ^0.15.0

flutter:
  uses-material-design: true

